module.exports = [
  {
    id: 1,
    first_name: "Zeid",
    surname: "Bsaibes",
    email: "random@gmail.com",
    password: "ilovelouis",
    avatar_url: "https://picsum.photos/200/200",
  },
  {
    id: 2,
    first_name: "Fioren",
    surname: "Nathasia",
    email: "random@gmail.com",
    password: "ilovelouis",
    avatar_url: "https://picsum.photos/200/200",
  },
  {
    id: 3,
    first_name: "Rory",
    surname: "Doak",
    email: "random@gmail.com",
    password: "ilovelouis",
    avatar_url: "https://picsum.photos/200/200",
  },
  {
    id: 4,
    first_name: "Yasmin",
    surname: "Unknown",
    email: "random@gmail.com",
    password: "ilovelouis",
    avatar_url: "https://picsum.photos/200/200",
  },
  {
    id: 5,
    first_name: "Anoushka",
    surname: "Patel",
    email: "random@gmail.com",
    password: "ilovelouis",
    avatar_url: "https://picsum.photos/200/200",
  },
  {
    id: 6,
    first_name: "Dominic",
    surname: "van D",
    email: "random@gmail.com",
    password: "ilovelouis",
    avatar_url: "https://picsum.photos/200/200",
  },
];
